openapi: 3.0.0
info:
  title: Smart Home Chatbot API
  version: 1.0.0
  description: Handles chatbot interactions and responses.

servers:
  - url: http://localhost:3013/api/v1

tags:
  - name: Chatbot

paths:
  /chat:
    post:
      tags: [Chatbot]
      summary: Get response from chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message]
              properties:
                message:
                  type: string
                  description: User's input message
      responses:
        200:
          description: Chatbot response
          content:
            application/json:
              example:
                reply: "Sure! Here's how you can reduce your energy usage..."
